#!/bin/bash
set -e

echo "==========================================="
echo "  TierMaker Production Setup Script"
echo "==========================================="
echo ""

# ── Check prerequisites ──
command -v node >/dev/null 2>&1 || { echo "Node.js is required. Install from https://nodejs.org"; exit 1; }
command -v git >/dev/null 2>&1 || { echo "Git is required."; exit 1; }

echo "[1/6] Installing dependencies..."
cd backend && npm ci && cd ..
cd frontend && npm ci && cd ..

echo ""
echo "[2/6] Generating Prisma client..."
cd backend && npx prisma generate && cd ..

echo ""
echo "==========================================="
echo "  Now configure your external services:"
echo "==========================================="
echo ""
echo "  STEP 3: Set up Neon PostgreSQL"
echo "  ─────────────────────────────────"
echo "  1. Go to https://console.neon.tech"
echo "  2. Create a new project named 'tiermaker'"
echo "  3. Copy the connection string"
echo "  4. Set DATABASE_URL in your deployment platform"
echo ""
echo "  STEP 4: Set up Upstash Redis"
echo "  ─────────────────────────────────"
echo "  1. Go to https://console.upstash.com"
echo "  2. Create a new Redis database"
echo "  3. Copy the Redis URL (rediss:// format)"
echo "  4. Set REDIS_URL in your deployment platform"
echo ""
echo "  STEP 5: Generate JWT secrets"
echo "  ─────────────────────────────────"
echo "  Run these commands and use the output:"
echo "    JWT_SECRET:         $(openssl rand -hex 64 2>/dev/null || echo 'openssl rand -hex 64')"
echo "    JWT_REFRESH_SECRET: $(openssl rand -hex 64 2>/dev/null || echo 'openssl rand -hex 64')"
echo ""
echo "  STEP 6: Deploy"
echo "  ─────────────────────────────────"
echo ""
echo "  Backend (choose one):"
echo ""
echo "    Railway:"
echo "      1. Install: npm i -g @railway/cli"
echo "      2. Login:   railway login"
echo "      3. Init:    cd backend && railway init"
echo "      4. Set env vars in Railway dashboard"
echo "      5. Deploy:  railway up"
echo ""
echo "    Render:"
echo "      1. Go to https://dashboard.render.com"
echo "      2. New → Web Service → Connect your repo"
echo "      3. Root Directory: backend"
echo "      4. Runtime: Docker"
echo "      5. Set env vars in Render dashboard"
echo "      6. Deploy"
echo ""
echo "  Frontend (Vercel):"
echo "      1. Install: npm i -g vercel"
echo "      2. Login:   vercel login"
echo "      3. Init:    cd frontend && vercel"
echo "      4. Set env vars in Vercel dashboard:"
echo "         - NEXT_PUBLIC_API_URL = your backend URL"
echo "         - NEXT_PUBLIC_WS_URL  = your backend URL"
echo "      5. Deploy:  vercel --prod"
echo ""
echo "  After deploying backend, run migrations:"
echo "    DATABASE_URL=your_neon_url npx prisma migrate deploy"
echo "    DATABASE_URL=your_neon_url npx ts-node src/prisma/seed.ts"
echo ""
echo "==========================================="
echo "  Setup complete!"
echo "==========================================="
